---
- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: download }

- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: k3s/master }

- hosts: node
  gather_facts: yes
  become: yes
  roles:
    - { role: k3s/node }
    - { role: drives }
