- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: download }
    - { role: k3s/master }

- hosts: node
  gather_facts: yes
  become: yes
  roles:
    - { role: download }
    - { role: k3s/node }

- hosts: agent
  gather_facts: yes
  become: yes
  roles:
    - { role: download }
    - { role: k3s/node }