- name: Copy K3s service file
  register: k3s_service
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  when: k3s_binary.changed or k3s_service.changed
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes