---
- name: Create brick path
  file:
    path: /data/bricks
    state: directory
- name: Create gluster volume
  gluster_volume:
    state: present
    name: shared
    bricks: /data/bricks/shared
    force: yes
    arbiters: 1
    replicas: 3
    cluster:
      - glusterfs-0.glusterfs.default.svc.cluster.local
      - glusterfs-1.glusterfs.default.svc.cluster.local
      - glusterfs-2.glusterfs.default.svc.cluster.local
  run_once: true